name: Docker Image CI

on: [release]

jobs:
  build:
    name: build orc
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker pull mgranderath/openwrt-build:0.1
    - name: Run the Docker image
      run: docker run --name openwrt_build_2 -v $(pwd):/restconf mgranderath/openwrt-build:0.1
